apiVersion: v1
kind: Pod
metadata:
  name: k8s-debug-pod
  labels:
    app: k8s-debug
spec:
  containers:
  - name: k8s-debug-container
    image: norelnorel3/k8s-debug-tools:1.0.0
    securityContext:
      privileged: false  
    env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TZ
      value: "UTC"
    - name: TITLE
      value: "K8s Debug Pod"
    - name: NGINX_DISABLE_IPV6
      value: "true"
    - name: CUSTOM_USER
      value: "user"
    - name: CUSTOM_PORT
      value: "3000"
    - name: SUBFOLDER
      value: "/"
    ports:
    - containerPort: 3000
      name: http
    - containerPort: 3001
      name: https
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
    volumeMounts:
    - name: config
      mountPath: /config
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: config
    emptyDir: {}
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 1Gi 
